### ISSUE TITLE
ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by yunzheng** [fox-it/flow.record#27]
When piping output from `rdump` to `head` you sometimes get the following stacktrace:

```shell
Traceback (most recent call last):
  File "/home/yun/.local/lib/python3.7/site-packages/flow/record/utils.py", line 57, in wrapper
    return func(*args, **kwargs)
  File "/home/yun/.local/lib/python3.7/site-packages/flow/record/tools/rdump.py", line 212, in main
    record_writer.write(rec)
  File "/home/yun/.local/lib/python3.7/site-packages/flow/record/adapter/csvfile.py", line 42, in write
    self.writer.writerow(rdict)
  File "/usr/lib/python3.7/csv.py", line 155, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yun/.local/bin/rdump", line 10, in <module>
    sys.exit(main())
  File "/home/yun/.local/lib/python3.7/site-packages/flow/record/utils.py", line 66, in wrapper
    os.dup2(devnull, sys.stdout.fileno())
ValueError: I/O operation on closed file
```

This seem to be caused by `sys.stdout` getting closed by `rdump` which should not happen.

**Comment by yunzheng** [comment]
Caused by `is_stdout()` not properly detecting normal `sys.stdout` as being `stdout`.
